### ISSUE TITLE
Request for port to Hubitat

### ISSUE THREAD

**Issue by mast76** [iquix/Smartthings#1]
Hi 

I have ported your ikea-tradfri-shortcut-button.groovy driver to the Hubitat hub.
Will you allow me to publish it on GitHub in my own repository?

Kind Regards,
Martin

**Comment by iquix** [comment]
Of course.
My DTH is just a little bit of modification from the original Smartthings zigbee-button DTH.

**Comment by iquix** [comment]
Hubitat port by @mast76 can be found here.
https://github.com/mast76/hubitat/blob/main/drivers/ikea-tradfri-shortcut-button.groovy
